### ISSUE TITLE
Additional documentation please

### ISSUE THREAD

**Issue by jefftrull** [8051Enthusiast/at51#2]
Hi! I'm very pleased to see this tool. Thank you for making it.

Unfortunately I am unclear on how to interpret the results. For example, the `stat` command says it "Shows statistical information about 8051 instruction frequency". There is also something in the README that explains that lower numbers are more indicative of 8051. But I'm still not sure what the two columns mean. I believe the first is an opcode, and maybe the second gives the chi-square value vs. some "expected" distribution? What sort of distributions would make you feel confident it was 8051 code? An example might help.

I have a similar concern about the libfind subcommand, where I am getting some output that I _assume_ means you've detected calls to library functions in the .LIB files I supplied. But I don't have the experience to determine whether it's accidental... maybe an example there? And/or add call counts - I think if I saw `(MAIN)` being called once but `?C?ULCMP` multiple times I might assume it was legitimate 8051 code and not noise... Thank you!

**Comment by 8051Enthusiast** [comment]
I tried to improve the documentation a bit, you can read it [here](https://github.com/8051Enthusiast/at51/tree/dev-0.4.0) and check if there are any places where you would need more documentation.

I also added an additional stat that works better by seeing how much the jumps are aligned to other instructions, as the previous ones didn't work that well.

I'm not sure how I would implement the call counts - the application doesn't know the general firmware structure/functions, it just matches functions found in the library to the firmware, so it can't know every occurence of calls/jumps globally.
I could maybe scan for raw ljmp/lcall in the firmware image, but that might produce some false negatives.

If I just count the references from other library segments, it might be confusing as perfectly fine segments can have 0 references.
Maybe then only do it for segments which are referenced but not there (i. e. in parens)?
I'm doubtful if showing functions in parens is useful at all - it is very useful for finding the main function and may be useful in the niche case that another library version was used and a referenced function slightly changed.
However, for sdcc firmware it leads to a bit of noise, and `?C_START` being there just because of an `ljmp` at the beginning might be confusing.

**Comment by jefftrull** [comment]
That's a great improvement! Thank you so much. I've decided that my binary file is, indeed, 8051 machine code in OMF-51 format, largely thanks to seeing your post on Twitter. Two days ago it was just a blob to me.

**Comment by 8051Enthusiast** [comment]
I guess you mean the binary file is compiled with OMF-51 libraries, because the files in OMF-51 are the library files and it would be unusual for a binary to be distributed in object format?

But anyways, glad I could help.

**Comment by jefftrull** [comment]
I think the binary may actually be OMF-51! At least, at the moment. It does begin with the "module" code (02) instead of the "library" code (2c) and if I'm reading the spec correctly this could be a reasonable way to supply code to a simple loader on the other end. Of course, I know next to nothing about this... looking forward to figuring it out.

**Comment by 8051Enthusiast** [comment]
Well, maybe it could be an AOMF file (like in the appendix of the OMF-51 specification) but 8051 firmware files also usually start with the byte 02, since it is the opcode of the ljmp opcode and the interrupt vector starts at 0x03, so jumping is pretty much the only thing that can be done.

**Comment by jefftrull** [comment]
I think you're right, upon further review. The record length field doesn't make sense, nor does the module name. The 02 is a red herring.
